### Register
POST http://localhost:8080/register
Content-Type: application/json
Accept: application/json

{
    "name":"Muhammad Handi Rachmawan",
    "email":"mail@handiism.id",
    "password": "p4ssword"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
    "email":"mail@handiism.id",
    "password": "p4ssword"
}

### Fetch
GET http://localhost:8080/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE
Accept: application/json


### Update
PATCH http://localhost:8080/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE
Accept: application/json

{
    "name":"nama baru",
    "email":"email@baru.id",
    "password": "p4sswordBARU"
}

### DELETE
DELETE  http://localhost:8080/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE


### Add List
POST http://localhost:8080/user/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE

{
    "title" : "Anjay"
}

### Get List
GET http://localhost:8080/user/list/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE

### Update List
PATCH http://localhost:8080/user/list/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE

{
    "title" : "Update nomor dua"
}

### Get All List
GET http://localhost:8080/user/list/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE

### Delete List
DELETE  http://localhost:8080/user/list/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYzg4ZGFhMDUtNWJlNC00NWEyLTg2ZTMtMTg3OWZiYmM1NDA5IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.pyJJM48zwVApOH6Fm4aQ8dP7o_UE_zev2NaIlAldXUE