version: "3"

dotenv: [".env"]

tasks:
  drop:
    ignore_error: true
    cmds:
      - PGPASSWORD=$DB_PASSWORD dropdb -U $DB_USER $DB_DATABASE
      - PGPASSWORD=$DB_PASSWORD dropdb -U $DB_USER $DB_DATABASE_TEST

  create:
    ignore_error: true
    cmds:
      - PGPASSWORD=$DB_PASSWORD createdb -U $DB_USER $DB_DATABASE
      - PGPASSWORD=$DB_PASSWORD createdb -U $DB_USER $DB_DATABASE_TEST

  migrate:
    ignore_error: true
    cmds:
      - PGPASSWORD=$DB_PASSWORD psql -o /dev/null -q -U $DB_USER $DB_DATABASE < schema.sql
      - PGPASSWORD=$DB_PASSWORD psql -o /dev/null -q -U $DB_USER $DB_DATABASE_TEST < schema.sql

  run:
    ignore_error: true
    cmds:
      - go run main.go
