### Register
POST http://localhost:8080/register
Content-Type: application/json
Accept: application/json

{
    "name":"Muhammad Handi Rachmawan",
    "email":"mail@handiism.id",
    "password": "p4ssword"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
    "email":"mail@handiism.id",
    "password": "p4ssword"
}

### Fetch
GET http://localhost:8080/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYWNlMTMzNDMtZTM3Yi00YzhmLWIyNzctZjA2MWIxMWU4NmQ1IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.eKuM_xSye-Zag9fV6FEJC0nSfRVvxI1mLnxLiBHwqdo
Accept: application/json


### Update
PATCH http://localhost:8080/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYWNlMTMzNDMtZTM3Yi00YzhmLWIyNzctZjA2MWIxMWU4NmQ1IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.eKuM_xSye-Zag9fV6FEJC0nSfRVvxI1mLnxLiBHwqdo
Accept: application/json

{
    "name":"nama baru",
    "email":"email@baru.id",
    "password": "p4sswordBARU"
}

### DELETE
DELETE  http://localhost:8080/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYWNlMTMzNDMtZTM3Yi00YzhmLWIyNzctZjA2MWIxMWU4NmQ1IiwiaXNzIjoiSGFuZGkgUmFjaG1hd2FuIn0.eKuM_xSye-Zag9fV6FEJC0nSfRVvxI1mLnxLiBHwqdo